import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"
[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
blur = false
option_as_alt = "OnlyLeft"

[window.padding]
x = 5
y = 2
[font]
size = 12.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[cursor]
style = "Beam"

[mouse]
hide_when_typing = true


[[keyboard.bindings]]
chars = ",*,x"
key = "x"
mods = "Command"

[[keyboard.bindings]]
chars = ",*,s"
key = "s"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "k"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "j"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "l"
mods = "Command"

