format = """
[](#2A2A37)\
$username\
[](bg:#363646 fg:#2A2A37)\
$git_branch\
$git_status\
[](fg:#363646 bg:#1f1f28)\
$directory\
[](fg:#1f1f28)\
"""

[username]
show_always=true
style_user = "bg:#2A2A37"
style_root = "bg:#2A2A37"
format = '[Benimaru ]($style)'


[directory]
style = "bg:#1f1f28"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#363646"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:#363646"
format = '[$all_status$ahead_behind ]($style)'


[time]
disabled = false
time_format = "%R" 
style = "bg:#2A2A37"
format = '[ $time ]($style)'
